/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeenuseTingimusedRouteImport } from './routes/teenuse-tingimused'
import { Route as PrivaatsuspoliitikaRouteImport } from './routes/privaatsuspoliitika'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogiIndexRouteImport } from './routes/blogi/index'
import { Route as BlogiSlugRouteImport } from './routes/blogi/$slug'

const TeenuseTingimusedRoute = TeenuseTingimusedRouteImport.update({
  id: '/teenuse-tingimused',
  path: '/teenuse-tingimused',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivaatsuspoliitikaRoute = PrivaatsuspoliitikaRouteImport.update({
  id: '/privaatsuspoliitika',
  path: '/privaatsuspoliitika',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogiIndexRoute = BlogiIndexRouteImport.update({
  id: '/blogi/',
  path: '/blogi/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogiSlugRoute = BlogiSlugRouteImport.update({
  id: '/blogi/$slug',
  path: '/blogi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privaatsuspoliitika': typeof PrivaatsuspoliitikaRoute
  '/teenuse-tingimused': typeof TeenuseTingimusedRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/blogi/': typeof BlogiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privaatsuspoliitika': typeof PrivaatsuspoliitikaRoute
  '/teenuse-tingimused': typeof TeenuseTingimusedRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/blogi': typeof BlogiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privaatsuspoliitika': typeof PrivaatsuspoliitikaRoute
  '/teenuse-tingimused': typeof TeenuseTingimusedRoute
  '/blogi/$slug': typeof BlogiSlugRoute
  '/blogi/': typeof BlogiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privaatsuspoliitika'
    | '/teenuse-tingimused'
    | '/blogi/$slug'
    | '/blogi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privaatsuspoliitika'
    | '/teenuse-tingimused'
    | '/blogi/$slug'
    | '/blogi'
  id:
    | '__root__'
    | '/'
    | '/privaatsuspoliitika'
    | '/teenuse-tingimused'
    | '/blogi/$slug'
    | '/blogi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivaatsuspoliitikaRoute: typeof PrivaatsuspoliitikaRoute
  TeenuseTingimusedRoute: typeof TeenuseTingimusedRoute
  BlogiSlugRoute: typeof BlogiSlugRoute
  BlogiIndexRoute: typeof BlogiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teenuse-tingimused': {
      id: '/teenuse-tingimused'
      path: '/teenuse-tingimused'
      fullPath: '/teenuse-tingimused'
      preLoaderRoute: typeof TeenuseTingimusedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privaatsuspoliitika': {
      id: '/privaatsuspoliitika'
      path: '/privaatsuspoliitika'
      fullPath: '/privaatsuspoliitika'
      preLoaderRoute: typeof PrivaatsuspoliitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogi/': {
      id: '/blogi/'
      path: '/blogi'
      fullPath: '/blogi/'
      preLoaderRoute: typeof BlogiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogi/$slug': {
      id: '/blogi/$slug'
      path: '/blogi/$slug'
      fullPath: '/blogi/$slug'
      preLoaderRoute: typeof BlogiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivaatsuspoliitikaRoute: PrivaatsuspoliitikaRoute,
  TeenuseTingimusedRoute: TeenuseTingimusedRoute,
  BlogiSlugRoute: BlogiSlugRoute,
  BlogiIndexRoute: BlogiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
